import React, {Component} from 'react';

export class Footer extends Component {
  render() {
    return (
      <footer>
        Built with ReactJS. Framework generated by <a href="https://github.com/orgs/FountainJS">FountainJS</a>.
      </footer>
    );
  }
}
